application: gaefrx
module: default
version: v1c
runtime: python27
api_version: 1
threadsafe: true

skip_files:
## The defaults
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
## The npm stuff to skip
- ^(.*/)node_modules/(.*/)


#
# Include sensitive information
#  not checked-in GIT repository
#
includes:
- secrets.yaml

handlers:

- url: /assets
  static_dir: assets
  
- url: /favicon.ico
  static_files: assets/favicon.ico
  upload: assets/favicon.ico

