application: gaefrx
module: default
version: v1d
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: ssl
  version: latest
- name: pycrypto
  version: latest
  
skip_files:
## The defaults
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
## The npm stuff to skip
- ^(.*/)node_modules/(.*/)


handlers:

- url: /assets
  static_dir: assets
  secure: always
  
- url: /favicon.ico
  static_files: assets/favicon.ico
  upload: assets/favicon.ico
  secure: always
